Fix WorkPage creation
* Switch models.ManyToManyField to ParentalManyToManyField to solve
  error

Traceback:

```
Internal Server Error: /admin/pages/add/core/workpage/4/
Traceback (most recent call last):
  File "/var/www/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/env/local/lib/python2.7/site-packages/newrelic-2.54.0.41/newrelic/hooks/framework_django.py", line 499, in wrapper
    return wrapped(*args, **kwargs)
  File "/var/www/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/var/www/env/local/lib/python2.7/site-packages/wagtail/wagtailadmin/decorators.py", line 22, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/var/www/env/local/lib/python2.7/site-packages/wagtail/wagtailadmin/views/pages.py", line 180, in create
    page = form.save(commit=False)
  File "/var/www/env/local/lib/python2.7/site-packages/modelcluster/forms.py", line 234, in save
    self.save_m2m()
  File "/var/www/env/local/lib/python2.7/site-packages/django/forms/models.py", line 434, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "/var/www/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1618, in save_form_data
    setattr(instance, self.attname, data)
  File "/var/www/env/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 480, in __set__
    manager = self.__get__(instance)
  File "/var/www/env/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 468, in __get__
    return self.related_manager_cls(instance)
  File "/var/www/env/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 751, in __init__
    (instance, self.source_field_name))
ValueError: "<WorkPage: test>" needs to have a value for field "workpage" before this many-to-many relationship can be used.
```