Fix uploading and searching images in admin
Upgrading Wagtail required an upgrade to Willow. This commit fixes
issues like this:

  TypeError: save_as_jpeg() got an unexpected keyword argument 'progressive'